version: '3'
services:
  web:
    build: ${APP_DOCKER_DIR}/web
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://web/
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
